#默认使用开发模式 (可使用 --spring.profiles.active=prod 切换环境)
server:
  port: 8081
#日志位置
logging:
  file: /data/appusr/ermas/logs/ermasBatch
  level:
    root: info
#elastic-job定义
elastic-job:
  regCenter:
    serverList: 127.0.0.1:2181
    namespace: elastic-My
  testSkip:
    jobName: testSkip
    desc: 测试testSkip
#    cron: 0/20 * * * * ?
    cron: 0/50 * * * * ?
    shardingTotalCount: 1
    interval: 6, 6, 6
    shardingItemParameters: 0=0|1|2,1=3|4|5,2=6|7|8|9
  simpleJob:
    jobName: mySimpleJob
    desc: 测试JOB
    cron: 0/20 * * * * ?
    shardingTotalCount: 1
    interval: 6, 6, 6
    shardingItemParameters: 0=0|1|2,1=3|4|5,2=6|7|8|9
regCenter:
#  serverList: localhost:6181
#  namespace: elastic-job-lite-springboot
  serverList: 127.0.0.1:2181
  namespace: elastic-My
datasource:
  slave:
    url: jdbc:mysql://127.0.0.1:3306/ermasdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: test
    password: test
















